baseURL = 'https://aichi.onrender.com/'
languageCode = 'en-us'
title = 'aichi.'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
